<?xml version="1.0" standalone="yes"?>
<pysystest type="auto" state="runnable">
    
  <description> 
    <title>Exception from PyUnit test</title>    
    <purpose><![CDATA[Ensure that we catch unexpected exceptions from PyUnit tests
and report them as failures.]]>
    </purpose>
  </description>

  <classification>
    <groups>
      <group>pyunit</group>
    </groups>
  </classification>

  <data>
    <class name="PySysTest" module="run"/>
  </data>
  
  <traceability>
    <requirements>
      <requirement id=""/>     
    </requirements>
  </traceability>
</pysystest>
