<?xml version="1.0" standalone="yes"?>
<pysystest type="auto" state="runnable">
    
  <description> 
    <title>Verify that exceptions thrown when files disappear during output directory scanning are ignored.</title>    
    <purpose><![CDATA[
    Various methods in the framework, e.g. TestContainer.detectCore(), iterate over all the files in the test output directory and perform some operation on each file.  If any output files are being manipulated by a background process it is possible that they may be deleted between being scanned by the directory iterator and whatever operation being performed.  An OSError will probably be thrown when this happens, which is fine except that in some cases this allowed the exception propogates up too far and causes the test to fail or block incorrectly.  This test verifies that these exceptions are ignored.
]]>
    </purpose>
  </description>

  <classification>
    <groups>
      <group></group>
    </groups>
  </classification>

  <data>
    <class name="PySysTest" module="run"/>
  </data>
  
  <traceability>
    <requirements>
      <requirement id=""/>     
    </requirements>
  </traceability>
</pysystest>
